apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBzSsOJFTZuzdvnanh1P9lhLSzSMmfsG2k8+C8SSAZCfm4gDPrdfp4ieYTb8OQNKxy1V+cljXv9NJP4jP9lc+l7Wutb4k3gicOoGgHHnf9miIsbxh3GUNVcT2SIe0lhSqtcJAHfqzOvBFHjszojzjKIhV1qaUIPOUDYvZb7IMbVBVtsAgNiJa/tgh8MBxPRCHdfeThZ+iAZ2rrmkvmC0QdjB+pT6I3D73LQLAMCdI2i7k3N+TXEFS0GCuzFnt/EZlXdaKC4y7p5MXI9utlAUZ4D21QbqVQaHmV+Zfm1hJGRBDaxMce06Q3V7qqPqDE62R1+vVXkfVijb78OwdoKv4ahE+4O49SIazZ8NR/emqWdwu7L1jj4GSR8VxEsbsv41X9FmGp7Dg8t1DvVsOOjM0CHEvblzhrzZyoHulN5uKGoOOFYYsanoFsF6uxCvVSxk4TaY1/MkvGiLZJMGt0GVhK/8OYYB3P51zAjIPFPcb6uVB0rQYQOqLFUWfm8WWLg9uTuvRHgt4k3ecLB+ItERhQ30rViAZ1Z+62Tkvb9oLhFW30GEacoVnVUP7jxtmTgOXG8gRWXKNmbNZK9Kc7A6zldMzGpMRpEmyvZhT8yrBOWiKcLM9ExDbnXhnh9ve1EBGraUgxTUWeBF9Lkdga6/CtRmYS1I87ftfggmMNxWFzM84ksi0p8xzatAf0tVls2xBgFM1h7Mq0yX1yniYEFRKenxL1ZG2Iw84FRm0XoX7ErQXL1CN5d/TREHQe6d6iuC2xUJvQy0uhQ8Fzs4d3VLhlg1FET6XawmMZZHC1QVRk3zaLp9M+rQZlX2mdliDV+mUAQa+ALGeZtbUg9VldetJPWu0BZt/udFwCklizaQ26WyvY/hJtgW4ekTfgHN7PpM9E5T5voHWH7m0wFyk8PxYU9x+gdnV9gmy+UqbyelJp0Kg==
    IBM_ENTITLED_REGISTRY_USER: AgCifNK11Pl1YcxMJ2ZsJNefzn8Waubiuz70v95bKcDlntbyWAwgXjMc8ZNkcIoQXJPyqzGan4f33Fv7lWeInJUwY31hID+RdsJObTs4zBkyyTqAjAWcd489FCGC4mX/pjLEMTI9JXG2GofPfnsENqi3T4A9FI7Ywg2o15W+pNBlDAfEJqfyzPe0XAhCcrKha9f46+7fFceaSIX99Ko+WpfoeXljlnpVazfVGHeU7gpg6ja0Qkt/4ZxbqJ2K8MppV3Svbx6TED2GHPXxUMR+3N77zlwHz9D7fAMoMK8d30vzq2VKbqUdCJUCh2WbP2hB8SkaxcU2nTYjr3vooczU05vfOXct90buOf8PBNmiSYbMvs2J7iT88u5bAHUyDq7Iq63DhHkFAEgLW6ghF3VQIJgUvrQUJu34TxoC6h2zf4AabD6NTGZKwr+0LrSBF9MLA2DFBBxWu0cDIk7HxUsfcBahYnPfNz2srX471lkzzcJwHZrSTDNNBeXq/c39YRJqRyoHX2EALkA5fjGvnJVfyDradMsDDz6KdMfhNnvZ3pWbNLer04wy917SH28KrRYQ9rLWO+6qfkDBYcetOvp/IhTUbd160t7FauWD11FF8IJgNheMn1rGMZQUE/YZk8ZkM2fUMRwcaQbjXeDo7wq9k9wkX4RadRYajwZUZSvRIJZnTGfgZoG1HzMvFfavlihxdWy4LQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

